#ifndef SIMON_MODELCOMPILATIONADAPTER_EXPORT_H_D56DDD9BBE944C24A6E2560A75AA881A
#define SIMON_MODELCOMPILATIONADAPTER_EXPORT_H_D56DDD9BBE944C24A6E2560A75AA881A

// needed for KDE_EXPORT and KDE_IMPORT macros
#include <kdemacros.h>

#ifndef MODELCOMPILATIONADAPTER_EXPORT
# if defined(MAKE_MODELCOMPILATIONADAPTER_LIB)
// We are building this library
#  define MODELCOMPILATIONADAPTER_EXPORT KDE_EXPORT
# else
// We are using this library
#ifdef Q_OS_WIN
#  define MODELCOMPILATIONADAPTER_EXPORT
#else
#  define MODELCOMPILATIONADAPTER_EXPORT KDE_IMPORT
#endif
# endif
#endif

# ifndef MODELCOMPILATIONADAPTER_EXPORT_DEPRECATED
#  define MODELCOMPILATIONADAPTER_EXPORT_DEPRECATED KDE_DEPRECATED MODELCOMPILATIONADAPTER_EXPORT
# endif
#endif
