#ifndef LANGUAGEMODELMANAGEMENT_EXPORT_H
#define LANGUAGEMODELMANAGEMENT_EXPORT_H
 
// needed for KDE_EXPORT and KDE_IMPORT macros
#include <kdemacros.h>
 
#ifndef LANGUAGEMODELMANAGEMENT_EXPORT
# if defined(MAKE_LANGUAGEMODELMANAGEMENT_LIB)
   // We are building this library
#  define LANGUAGEMODELMANAGEMENT_EXPORT KDE_EXPORT
# else
   // We are using this library
#  define LANGUAGEMODELMANAGEMENT_EXPORT KDE_IMPORT
# endif
#endif
 
# ifndef LANGUAGEMODELMANAGEMENT_EXPORT_DEPRECATED
#  define LANGUAGEMODELMANAGEMENT_EXPORT_DEPRECATED KDE_DEPRECATED LANGUAGEMODELMANAGEMENT_EXPORT
# endif
 
#endif
