#ifndef SIMON_MODELMANAGEMENT_EXPORT_H_A1550CB3A9E14558809B5F394C2D23D9
#define SIMON_MODELMANAGEMENT_EXPORT_H_A1550CB3A9E14558809B5F394C2D23D9
 
// needed for KDE_EXPORT and KDE_IMPORT macros
#include <kdemacros.h>
 
#ifndef MODELMANAGEMENT_EXPORT
# if defined(MAKE_MODELMANAGEMENT_LIB)
   // We are building this library
#  define MODELMANAGEMENT_EXPORT KDE_EXPORT
# else
   // We are using this library
	//#ifdef Q_OS_WIN
	//#  define MODELMANAGEMENT_EXPORT
	//#else
	#  define MODELMANAGEMENT_EXPORT KDE_IMPORT
	//#endif
# endif
#endif
 
# ifndef MODELMANAGEMENT_EXPORT_DEPRECATED
#  define MODELMANAGEMENT_EXPORT_DEPRECATED KDE_DEPRECATED MODELMANAGEMENT_EXPORT
# endif
 
#endif
