#ifndef SIMON_SIMONCONTEXTDETECTION_EXPORT_H_F1032DFE61FA42E3B31933515AF33099
#define SIMON_SIMONCONTEXTDETECTION_EXPORT_H_F1032DFE61FA42E3B31933515AF33099

// needed for KDE_EXPORT and KDE_IMPORT macros
#include <kdemacros.h>
#include <KDE/KGenericFactory>

#ifndef SIMONCONTEXTDETECTION_EXPORT
# if defined(MAKE_SIMONCONTEXTDETECTION_LIB)
// We are building this library
#  define SIMONCONTEXTDETECTION_EXPORT KDE_EXPORT
# else
// We are using this library
#  define SIMONCONTEXTDETECTION_EXPORT
# endif
#endif

# ifndef SIMONCONTEXTDETECTION_EXPORT_DEPRECATED
#  define SIMONCONTEXTDETECTION_EXPORT_DEPRECATED KDE_DEPRECATED SIMONCONTEXTDETECTION_EXPORT
# endif
#endif
