#ifndef SIMON_SIMONCOMMANDPLUGINBASE_EXPORT_H_D44EAE2C67DA4E0D948C5CC74EC3534D
#define SIMON_SIMONCOMMANDPLUGINBASE_EXPORT_H_D44EAE2C67DA4E0D948C5CC74EC3534D
 
// needed for KDE_EXPORT and KDE_IMPORT macros
#include <kdemacros.h>
#include <KGenericFactory>
 
#ifndef SIMONCOMMANDPLUGINBASE_EXPORT
# if defined(MAKE_SIMONCOMMANDPLUGINBASE_LIB)
   // We are building this library
#  define SIMONCOMMANDPLUGINBASE_EXPORT KDE_EXPORT
# else
   // We are using this library
#  define SIMONCOMMANDPLUGINBASE_EXPORT KDE_IMPORT
# endif
#endif
 
# ifndef SIMONCOMMANDPLUGINBASE_EXPORT_DEPRECATED
#  define SIMONCOMMANDPLUGINBASE_EXPORT_DEPRECATED KDE_DEPRECATED SIMONCOMMANDPLUGINBASE_EXPORT
# endif

  

#endif
