#ifndef SIMON_SIMONDDATABASEACCESS_EXPORT_H_200C0FC8F1764B149BA2B15E090BD5CE
#define SIMON_SIMONDDATABASEACCESS_EXPORT_H_200C0FC8F1764B149BA2B15E090BD5CE

// needed for KDE_EXPORT and KDE_IMPORT macros
#include <kdemacros.h>

#ifndef SIMONDDATABASEACCESS_EXPORT
# if defined(MAKE_SIMONDDATABASEACCESS_LIB)
// We are building this library
#  define SIMONDDATABASEACCESS_EXPORT KDE_EXPORT
# else
// We are using this library
#  define SIMONDDATABASEACCESS_EXPORT
# endif
#endif

# ifndef SIMONDDATABASEACCESS_EXPORT_DEPRECATED
#  define SIMONDDATABASEACCESS_EXPORT_DEPRECATED KDE_DEPRECATED SIMONDDATABASEACCESS_EXPORT
# endif
#endif
