#ifndef SIMON_ADINSTREAMER_EXPORT_H_FFC5CEA9FBF74C52838C3684F20E0423
#define SIMON_ADINSTREAMER_EXPORT_H_FFC5CEA9FBF74C52838C3684F20E0423
 
// needed for KDE_EXPORT and KDE_IMPORT macros
#include <kdemacros.h>
 
#ifndef ADINSTREAMER_EXPORT
#if defined(MAKE_ADINSTREAMER_LIB)
   // We are building this library
#  define ADINSTREAMER_EXPORT KDE_EXPORT
# else
   // We are using this library
  #ifdef Q_OS_WIN
    #define ADINSTREAMER_EXPORT KDE_IMPORT
  #else
    #define ADINSTREAMER_EXPORT
  # endif
#endif
#endif
 
# ifndef ADINSTREAMER_EXPORT_DEPRECATED
#  define ADINSTREAMER_EXPORT_DEPRECATED KDE_DEPRECATED ADINSTREAMER_EXPORT
# endif
 
#endif
