// This file is generated by kconfig_compiler from simon.kcfg.
// All changes you do to this file will be lost.

#include "simon.h"

#include <kglobal.h>
#include <QtCore/QFile>

class CoreConfigurationHelper
{
  public:
    CoreConfigurationHelper() : q(0) {}
    ~CoreConfigurationHelper() { delete q; }
    CoreConfiguration *q;
};
K_GLOBAL_STATIC(CoreConfigurationHelper, s_globalCoreConfiguration)
CoreConfiguration *CoreConfiguration::self()
{
  if (!s_globalCoreConfiguration->q) {
    new CoreConfiguration;
    s_globalCoreConfiguration->q->readConfig();
  }

  return s_globalCoreConfiguration->q;
}

CoreConfiguration::CoreConfiguration(  )
  : KConfigSkeleton()
{
  Q_ASSERT(!s_globalCoreConfiguration->q);
  s_globalCoreConfiguration->q = this;
}

CoreConfiguration::~CoreConfiguration()
{
  if (!s_globalCoreConfiguration.isDestroyed()) {
    s_globalCoreConfiguration->q = 0;
  }
}

