// This file is generated by kconfig_compiler from simon.kcfg.
// All changes you do to this file will be lost.
#ifndef CORECONFIGURATION_H
#define CORECONFIGURATION_H

#include <kconfigskeleton.h>
#include <kdebug.h>

class CoreConfiguration : public KConfigSkeleton
{
  public:

    static CoreConfiguration *self();
    ~CoreConfiguration();

  protected:
    CoreConfiguration();
    friend class CoreConfigurationHelper;


  private:
};

#endif

