#ifndef SIMON_SIMONCOMMANDPLUGINBASE_EXPORT_H_26141F0F1EE1469593E847EAD925285C
#define SIMON_SIMONCOMMANDPLUGINBASE_EXPORT_H_26141F0F1EE1469593E847EAD925285C
 
// needed for KDE_EXPORT and KDE_IMPORT macros
#include <kdemacros.h>
#include <KGenericFactory>
 
#ifndef SIMONCOMMANDPLUGINBASE_EXPORT
# if defined(MAKE_SIMONCOMMANDPLUGINBASE_LIB)
   // We are building this library
#  define SIMONCOMMANDPLUGINBASE_EXPORT KDE_EXPORT
# else
   // We are using this library
#  define SIMONCOMMANDPLUGINBASE_EXPORT KDE_IMPORT
# endif
#endif
 
# ifndef SIMONCOMMANDPLUGINBASE_EXPORT_DEPRECATED
#  define SIMONCOMMANDPLUGINBASE_EXPORT_DEPRECATED KDE_DEPRECATED SIMONCOMMANDPLUGINBASE_EXPORT
# endif

  

#endif
