#ifndef SIMONPOSTPROCESSING_EXPORT_H
#define SIMONPOSTPROCESSING_EXPORT_H
 
// needed for KDE_EXPORT and KDE_IMPORT macros
#include <kdemacros.h>
 
#ifndef SIMONPOSTPROCESSING_EXPORT
# if defined(MAKE_SIMONPOSTPROCESSING_LIB)
   // We are building this library
#  define SIMONPOSTPROCESSING_EXPORT KDE_EXPORT
# else
   // We are using this library
#  define SIMONPOSTPROCESSING_EXPORT KDE_IMPORT
# endif
#endif
 
# ifndef SIMONPOSTPROCESSING_EXPORT_DEPRECATED
#  define SIMONPOSTPROCESSING_EXPORT_DEPRECATED KDE_DEPRECATED SIMONPOSTPROCESSING_EXPORT
# endif
 

#endif