#ifndef SIMONRECOGNIONRESULT_EXPORT_H
#define SIMONRECOGNIONRESULT_EXPORT_H
 
// needed for KDE_EXPORT and KDE_IMPORT macros
#include <kdemacros.h>
#include <KGenericFactory>
 
#ifndef SIMONRECOGNIONRESULT_EXPORT
# if defined(MAKE_SIMONRECOGNIONRESULT_LIB)
   // We are building this library
#  define SIMONRECOGNIONRESULT_EXPORT KDE_EXPORT
# else
   // We are using this library
#  define SIMONRECOGNIONRESULT_EXPORT KDE_IMPORT
# endif
#endif
 
# ifndef SIMONRECOGNIONRESULT_EXPORT_DEPRECATED
#  define SIMONRECOGNIONRESULT_EXPORT_DEPRECATED KDE_DEPRECATED SIMONRECOGNIONRESULT_EXPORT
# endif

  

#endif
