#ifndef SIMON_SIMONGREEDYRECEIVER_EXPORT_H_6EE7AB4564D14A5B803E104938A8165B
#define SIMON_SIMONGREEDYRECEIVER_EXPORT_H_6EE7AB4564D14A5B803E104938A8165B
 
// needed for KDE_EXPORT and KDE_IMPORT macros
#include <kdemacros.h>
#include <KGenericFactory>
 
#ifndef SIMONGREEDYRECEIVER_EXPORT
# if defined(MAKE_SIMONGREEDYRECEIVER_LIB)
   // We are building this library
#  define SIMONGREEDYRECEIVER_EXPORT KDE_EXPORT
# else
   // We are using this library
#  define SIMONGREEDYRECEIVER_EXPORT KDE_IMPORT
# endif
#endif
 
# ifndef SIMONGREEDYRECEIVER_EXPORT_DEPRECATED
#  define SIMONGREEDYRECEIVER_EXPORT_DEPRECATED KDE_DEPRECATED SIMONGREEDYRECEIVER_EXPORT
# endif

  

#endif
