#ifndef SIMON_SIMONDSTREAMER_EXPORT_H_FFC5CEA9FBF74C52838C3684F20E0423
#define SIMON_SIMONDSTREAMER_EXPORT_H_FFC5CEA9FBF74C52838C3684F20E0423
 
// needed for KDE_EXPORT and KDE_IMPORT macros
#include <kdemacros.h>
 
#ifndef SIMONDSTREAMER_EXPORT
#if defined(MAKE_SIMONDSTREAMER_LIB)
   // We are building this library
#  define SIMONDSTREAMER_EXPORT KDE_EXPORT
# else
   // We are using this library
  #ifdef Q_OS_WIN
    #define SIMONDSTREAMER_EXPORT KDE_IMPORT
  #else
    #define SIMONDSTREAMER_EXPORT
  # endif
#endif
#endif
 
# ifndef SIMONDSTREAMER_EXPORT_DEPRECATED
#  define SIMONDSTREAMER_EXPORT_DEPRECATED KDE_DEPRECATED SIMONDSTREAMER_EXPORT
# endif
 
#endif
