FIND_PATH(ATSPI_INCLUDE_DIR atspi.h PATHS /usr/include/at-spi-2.0 PATH_SUFFIXES atspi)

FIND_LIBRARY(ATSPI_LIBRARY NAMES atspi PATH /usr/lib /usr/local/lib) 

IF (ATSPI_INCLUDE_DIR AND ATSPI_LIBRARY)
   SET(ATSPI_FOUND TRUE)
ENDIF (ATSPI_INCLUDE_DIR AND ATSPI_LIBRARY)


IF (ATSPI_FOUND)
   IF (NOT ATSPI_FIND_QUIETLY)
      MESSAGE(STATUS "Found ATSPI: ${ATSPI_LIBRARY}")
   ENDIF (NOT ATSPI_FIND_QUIETLY)
ELSE (ATSPI_FOUND)
   IF (ATSPI_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find ATSPI")
   ENDIF (ATSPI_FIND_REQUIRED)
ENDIF (ATSPI_FOUND)


